### ISSUE TITLE
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_8.1.1-2ubuntu0.2_all.deb  404  Not Found [IP: 91.189.88.162 80]

### ISSUE THREAD

**Issue by mkg20001** [chihchun/snapcraft-docker#2]
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_8.1.1-2ubuntu0.2_all.deb  404  Not Found [IP: 91.189.88.162 80]
```
(Can not install python-pip because of this error)
The package lists need to be updated.
Rebuilding the Container should fix that...

**Comment by chihchun** [comment]
Could you let me know which version of the docker image you were using?

**Comment by mkg20001** [comment]
```
maciej@maciej-pc:~$ docker pull snapcraft/xenial-amd64:latest
latest: Pulling from snapcraft/xenial-amd64
Digest: sha256:49e8afe2102849c44d0779a94b446c3cfa9928a13f9268dd64ed085c96e5d831
Status: Image is up to date for snapcraft/xenial-amd64:latest
```

**Comment by chihchun** [comment]
rebuilt the latest adm64 and i386 version, thanks for reporting

**Comment by jeromeheissler** [comment]
The problem is back :
`E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/g/git/git_2.7.4-0ubuntu1.1_armhf.deb  404  Not Found [IP: 91.189.88.150 80]`

**Comment by mkg20001** [comment]
I think the only good solution would be to rebuild the image every once in a while or to run `apt update` before running snapcraft
